### PR TITLE
vite, jest, ESM, ES classes

### PR DESCRIPTION
**Pull request by dmvjs**
need to verify that built files dont have any issues
all tests pass

### CODE REVIEW

**Comment by perak** [comment]
Ouch! A lof of for review 😄 

Note that tests are not exhaustive (actually, tests are minimal), and we use this package in multiple projects internally (yes, technical debt it is), so I need to carefully test before merging.

Thank you for this btw! Project started when ES6 was beta and not widelly supported by browsers and node. But we really need to modernize it.

**Comment by dmvjs** [comment]
Thanks for taking a look, no rush from my side I just got excited about this repo and thought I could contribute. I know it is a huge PR and I can break it up any way you like if it is helpful.  

Upgrading dependencies and modernizing JS repos is kind of my thing. If I can find a good way to test the built files I will.

**Comment by dmvjs** [comment]
I'm not sure if you have had any time to test this yet, but I can peel it off into layers if that is more helpful. I didn't intend for the PRs to collapse into a single one, apologies.

**Comment by perak** [comment]
@dmvjs I merged this pull request into [modernizing](https://github.com/quantastica/quantum-circuit/tree/modernizing) branch.

We have multiple issues with our other tools, mostly related to version of nodejs and/or mixing JS with ES, so I cannot merge into `master` yet.

Let's move forward in `modernizing` branch.

Thank you!

**Pull request closed without merging**
